### PR TITLE
Support normalization of line endings

### PR DESCRIPTION
**Pull request by ofek**
Please fill in the fields below to submit a pull request.  The more information
that is provided, the better.

**Fixes issue #**:

No cross-platform support

**Description of the changes being introduced by the pull request**:

**Please verify and check that the pull request fulfills the following
requirements**:

- [ ] The code follows the [Code Style Guidelines](https://github.com/secure-systems-lab/code-style-guidelines#code-style-guidelines)
- [ ] Tests have been added for the bug fix or new feature
- [ ] Docs have been added for the bug fix or new feature

### CODE REVIEW

**Comment by trishankatdatadog** [comment]
Looks great, thanks, @ofek! Does this address newlines on boundaries, do you know?

**Comment by ofek** [comment]
Yes

**Comment by trishankatdatadog** [comment]
Dumb question: what if the nth chunk ends with `\r` and the (n+1)th chunk begins with `\n` and we're on Windows?

**Comment by ofek** [comment]
Yes and that case is tested (full coverage)

**Comment by awwad** [comment]
Mechanically:
On a quick glance, it looks right mechanically. Also, there are no resulting TUF or in-toto test failures I've seen (locally, 2.7 and 3.6 TUF, 2.7 in-toto). I doubt the tests encounter these cases (not sure if we should add some), but it means we didn't break anything, so that's good.

Conceptually, I'm a little worried, since this means that the hashes of these two things hash equivalently. If someone knows this, they can swap in one for the other.... (LMK if my thinking is off.)

turtle
turtle-equivalent

This might be too low-level a place to put this code?

**Comment by SantiagoTorres** [comment]
So, the motivation for this change follows the git usecase, in which windows uses \r\n line-endings to files, whereas *nix uses \n. This would happen, which is troublesome, but it's up to the applications to make sure the replacement only happens on *text* files, where `\n` and `\r\n` have a distinctive usecase.

**Comment by awwad** [comment]
I'll think about it a little more and look at the stacks this lives in this afternoon, but I think that normalizing data is something that should happen at a higher level, or, at the least, be non-default and well-documented.

**Comment by trishankatdatadog** [comment]
Our thinking is that in-toto (and, by extension, securesystemslib) should handle this, but we also do not think that this should happen automagically for everyone, which is why we are advocating for the flag approach. We do not think that in-toto integrators should be explicitly aware, by default, of "interesting" edge cases such as this.

@ofek Please let me know if I misunderstood anything.

**Comment by awwad** [comment]
My bad: somehow managed to read that the default was to normalize. It's not, so I'm OK with this. :) I'll take one more look and I should be able to merge it shortly this afternoon.

**Pull request merged**
