### PR TITLE
Remove schema facility and most of formats

### LINKED ISSUE #183: Revise schema and formats facility
**Description of issue or feature request**:
Here are several loosely ordered observations in regards to securesystemslib's [schema](https://github.com/secure-systems-lab/securesystemslib/blob/v0.11.2/securesystemslib/formats.py)/[formats](https://github.com/secure-systems-lab/securesystemslib/blob/v0.11.2/securesystemslib/schema.py) facility:

**Current behavior**:
- Some schemas **sound more specific than they are**, e.g. `RELPATH_SCHEMA == PATH_SCHEMA == AnyString`. This is misleading, when assessing a function's capability of sanitizing inputs.

- Some schemas are an **odd replacement for constants**, e.g. schemas that define hard-coded strings, like `"rsassa-pss-sha256"`, and are then used to check the same strings, which have been hardcoded into function default arguments.

- Schema validation seems generally **overused**.  In TUF nearly every function runs `check_match` for each argument. IMHO argument sanitizing is mostly important in public-facing interfaces. Programming errors, on the other, should be caught through extensive testing and code review.
Using it everywhere makes the code bloated, also because there are a lot of generic comments describing the checks, and the obligatory and also quite generic `FormatError, if <arg> is not properly formatted`- blocks in the `<Exceptions>` section of docstrings. 

- Schema checking sometimes makes **execution branches unreachable**  (also see https://github.com/secure-systems-lab/code-style-guidelines/issues/18):

  ```python
  X_OR_Y_SCHEMA.check_match(arg)

  if arg == X:
    # ...
  elif arg == Y:
    # ...
  else:
    raise WillNeverBeRaisedError()
  ```
  And I've even seen cases where `WillNeverBeRaisedError` is also listed in the docstring as Exception that might be raised (documentation rot)

- The error messages from checking schemas with the `check_match` method are often not helpful, because they usually don't show the value of the checked variable or lack context.

**Expected behavior**:

- Review existing schemas for their validity/strictness, especially when chained.

- Only use in public facing interfaces (open for discussion). 
This would also require a clearer definition of what functions should be public interfaces, which btw. TUF/in-toto integrators would greatly benefit from.

- At least don't blindly  add `<arg>.<SCHEMA>.check_match` to every function. Coordinate with the rest of the function, and its purpose.

- Make sure the error message is helpful, e.g. by:
  - supporting an error message override argument in `check_match`, or by
  - using `matches` plus `raise FormatError` (or maybe even just `ValueError`) with a custom message instead of `check_match`.

- Disambiguate schemas and constants.

### PR DESCRIPTION
**Pull request by lukpueh**
- addresses part of [#731](https://github.com/secure-systems-lab/securesystemslib/issues/731)
- ~blocks on [#773](https://github.com/secure-systems-lab/securesystemslib/pull/773),  [#774](https://github.com/secure-systems-lab/securesystemslib/pull/774),  [#775](https://github.com/secure-systems-lab/securesystemslib/pull/775) (commits are included in this PR)~

close #183 

---

The usage of the securesystemslib schema/formats facility has been little by little phased out and is now nowhere used anymore. Several reasons to not use it are listed in https://github.com/secure-systems-lab/securesystemslib/issues/183.

This patch removes schema.py along with all securesystemslib schema definitions in formats.py.

Additionally, it removes unrelated and unused helper functions in formats.py.

### CODE REVIEW

**Comment by lukpueh** [comment]
Some windows runners seem to calculate test coverage differently than the rest and thus drop below the already lowered constraint. I'll fix this, when this PR is no longer blocked by other PRs.

**Comment by lukpueh** [comment]
> Some windows runners seem to calculate test coverage differently than the rest and thus drop below the already lowered constraint.

9be1638 further lowers the coverage requirement. As before, this does not mean that there are fewer tests (see commit message).

**Comment by jku** [comment]
> this does not mean that there are fewer tests (see commit message).

Some of the bad coverage is quite expected (aws, azure, gcp, sigstore). I was surprised that HSMSigner is the worst though -- I wonder what that's about.

**Review by jku — APPROVED** [review]

**Comment by lukpueh** [comment]
> > this does not mean that there are fewer tests (see commit message).
> 
> Some of the bad coverage is quite expected (aws, azure, gcp, sigstore). I was surprised that HSMSigner is the worst though -- I wonder what that's about.

https://github.com/secure-systems-lab/securesystemslib/blob/37089c53cde6842a5224b0b2cac90644a8d753df/.github/workflows/_test.yml#L62-L64

**Pull request merged**
