### PR TITLE
Make GPGSigner.sign return Signature

### LINKED ISSUE #448: GPGSigner (and gpg.functions.create_signature) produce invalid signature dicts
```python
        signer = GPGSigner(self.signing_subkey_keyid, self.gnupg_home)
        signature = signer.sign(self.test_data)
        print(signature.to_dict())
```
The result does not look like a TUF compliant signature (notice the key name "signature" instead of "sig"):
```
{
  'keyid': 'c5a0abe6ec19d0d65f85e2c39be9df5131d924e9',
  'signature': '5630c9b9436ed438cdf1386abe9ca3201612c24dee868e7294f6f4592fa05820a194cf1f87fd21f5ea0a596578a20491ca8829ef8d352df1139a953e28cf2176e3c3dc484e669782f65a1cc7ac4d1798ef3874e1f4a113aa59e5b6d350aacfa3c9c58a3ef2770995396971db3aae93d122a73795bb6b6b8d6e5b49a9be64bed8c13f849b09d43c7e916366a6290e92e41987636107703147b2fc86eec59909ddf1d002f39655c11176c18f04b927ecce48781258aa4e8f715014e2e30332839475528afa7faac0c48b425984eb726176092a2cbc3ece7d7e7eea372b8ffdf82715564536b961e5d195f1746b578ccaea19a5eb5936a2d38e0187af490ecc902a',
  'other_headers': '04000108001d162104c5a0abe6ec19d0d65f85e2c39be9df5131d924e90502635bbb2e'
}
```

Did no-one ever actually try to put a GPG signature in TUF metadata?

### LINKED ISSUE #471: Move GPGSigner to intoto
I think the plan is as follows (@lukpueh can correct):
* Move GPGSigner from securesystemslib to somewhere under intoto umbrella
* Also add GPGKey in the same place
* intoto can then use the new dispatch mechanisms (from #456) to support gpg in intoto with just a small amoun of hacks
  * e.g. use (None, None) as the keytype/scheme-tuple
  * handle the special keyid matching  

This is done because the gpg key and signature have serialization formats that are not quite compatible with the specifications. The goal is:
* intoto can keep supporting the current key and sig formats for backwards compat
* we can later add more specification compatible GPG support into securesystemslib (but this won't be compatible with the format in intoto)

### PR DESCRIPTION
**Pull request by lukpueh**
Fixes #448
Closes #471 

### Description of the changes being introduced by the pull request:

GPGSigner.sign now returns Signature, which maps to a in-toto and tuf spec compliant signature object. The lower level gpg signing and verifying API stays as is, to allow existing gpg users (in-toto) to create and verify signature using the old format.

This is an acceptable API break, because GPGSigner is not yet used by in-toto or python-tuf.

To make `GPGSigner` useable for tuf and DSSE ([#370](https://github.com/secure-systems-lab/securesystemslib/issues/370)) a spec compatible GPGKey implementation will be added in a follow-up PR.

### Please verify and check that the pull request fulfils the following requirements:

- [ ] The code follows the [Code Style Guidelines](https://github.com/secure-systems-lab/code-style-guidelines#code-style-guidelines)
- [ ] Tests have been added for the bug fix or new feature
- [ ] Docs have been added for the bug fix or new feature

### CODE REVIEW

**Review by jku — APPROVED** [review]
Seems good to me.

**Comment by jku** [comment]
Although: the serialized signature format contains some extra fields when created with GPGSigner, right? It would be nice if these were obvious in the tests

**Comment by lukpueh** [comment]
@jku, let me know if the last commit roughly aligns with what you had in mind.

**Comment by jku** [comment]
Yeah LGTM. It's not clear from the test what is actually in the custom data but it's now visible to reader that there's something there: I'm happy with that.

**Pull request merged**
