### PR TITLE
.pre-commit-config.yaml updated with ruff

### LINKED ISSUE #831: modify pre-commit-config.yaml
As of moving the project to the ruff linter, `pre-commit-config.yaml` should be modified: 

- remove isort and black from pre-commit
- add ruff into pre-commit

related: #829

### PR DESCRIPTION
**Pull request by L77H**
**Description of the changes being introduced by the pull request**:

- isort removed from pre-commit
- black removed rom pre-commit
- ruff added to pre-commit
- ruff-format added to pre-commit

see also: https://github.com/astral-sh/ruff-pre-commit

Fixes #831

### CODE REVIEW

**Review by jku — COMMENTED** [review]
Nice. I wonder if this should run ruff with `--fix`?

I dont use pre-commit so I'm not sure

**Comment by L77H** [comment]
As I understand when using `--fix` it immediately fixes any fixable errors, while without `--fix` it just outputs the linting errors.

see: https://docs.astral.sh/ruff/linter/#ruff-check

**Comment by jku** [comment]
Looks good to me but I'll let Lukas approve this next week as  I think he uses pre-commit

**Comment by lukpueh** [comment]
Thanks for the patch, @L77H! I'm okay, if we remove the pre-commit config entirely as discussed here: https://github.com/secure-systems-lab/securesystemslib/issues/734

**Comment by L77H** [comment]
I have removed the pre-commit config file entirely.

**Review by jku — APPROVED** [review]
thanks!

**Pull request merged**
