### PR TITLE
Use __future__.annotations module

### PR DESCRIPTION
**Pull request by jku**
The extra import is a little annoying but allows using even python 3.10 annotation features already, which I like.
* start using "X | None" instead of Optional[X]
* Drop the quotes from factory function return values

This also keeps us compatible with python 3.8 for the moment.

### CODE REVIEW

**Comment by jku** [comment]
Not quite sure who is available for review: flagged @adityasaky but no problem if you're not available

**Comment by jku** [comment]
would make sense to drop this back to 3.8 now :

`requires-python = "~=3.9"`

**Review by adityasaky — APPROVED** [review]
This looks good to me though I must note I may not qualify as an "expert reviewer" in python's type hints.

Also, is support for 3.8 a requirement somewhere?

**Comment by jku** [comment]
> Also, is support for 3.8 a requirement somewhere?

No, and I would even say it's not supported: I just don't want to be the first one to explicitly break potential 3.8 users if it's easy to avoid.

**Pull request merged**
