### PR TITLE
add migrate_key cli script

### PR DESCRIPTION
**Pull request by lukpueh**
This is in preparation for the removal of legacy key modules and formats, in favor of the new Signer API. It allows users to convert their old rsa, ed25519 and ecdsa key files, generated with the `interface` or `keys` module, and using an outdated standard or sslib proprietary format (see #309), to a consistent new standard format, which can be used with the file-based signer (`CryptoSigner`) of the new Signer API.

NOTE: The script uses legacy code and should thus be removed with them, from the repo tree, while remaining available to users of securesystemslib for some time. We could keep pointing to it in docs after its removal (users would need to check-out the repo at a specified tag), or move it to a different place.

**Change details**
* Add cli script to convert key files.
* Add private/private encrypted/public test key files for each supported algorithm in the legacy format. *The key pairs were generated with `interface`, minimally modified to allow writing an encrypted and non-encrypted version of the same private key.*
* Add comprehensive tests, includes backwards/forward compatibility of signatures.

### CODE REVIEW

**Comment by jku** [comment]
I don't object to the functionality but I have some questions:
* does this need to be part of the API? does it need to be part of the wheel or could it just be in git tree without getting packaged?
* if it's a CLI script and should be part of the wheel, should it be packaged as `script` or `entry_point` (and so the module could be internal)

I'm a little surprised I can't get mypy to complain about the lack of typing (even if I add the file to the config) but I don't know if that's something you should spend time on...

**Comment by lukpueh** [comment]
> * does this need to be part of the API? does it need to be part of the wheel or could it just be in git tree without getting packaged?

Git tree only is fine. It certainly does not have to be part of the public API/CLI, or even packaged. I really just wanted to add it to the "securesystemslib" namespace, piggyback on its ci, and show that it passes at least once.

My idea was to tag it, remove it, but keep it in the docs for a while, including the tag at which it can be used.

In reality, the script is unlikely to have a lot of users, and it's simple enough, so I might as well just throw it in a personal gist. What do you think?

**Comment by jku** [comment]
I don't have strong opinions, any of those sounds fine. Could drop it in docs/ or examples/ as well :shrug: .

**Comment by lukpueh** [comment]
@jku, would you kindly approve?

I moved the script to docs/ and added a small pointer to README.

**Review by jku — APPROVED** [review]

**Pull request merged**
