### PR TITLE
AzureSigner: import_ may return *unsupported* ecdsa-sha2-nistp521 scheme

### LINKED ISSUE #764: AzureSigner: import_ may return *unsupported* ecdsa-sha2-nistp521 scheme
`AzureSigner.import_` supports importing a public key on curve nistp521, and returns it as SSlibKey with scheme "ecdsa-sha2-nistp521".

https://github.com/secure-systems-lab/securesystemslib/blob/185aa9cedeb6597c40be62d938297c75d1f930a0/securesystemslib/signer/_azure_signer.py#L215-L216

`SSlibKey.verify_signature`, however, only supports nistp256 and nistp384 key:

https://github.com/secure-systems-lab/securesystemslib/blob/185aa9cedeb6597c40be62d938297c75d1f930a0/securesystemslib/signer/_key.py#L382-L385

**Possible fixes**
* remove support for "ecdsa-sha2-nistp521" in AzureSigner.import_
* add support for "ecdsa-sha2-nistp521" in SSlibKey.verify_signature
* orthogonal: validate scheme in `SSlibKey.__init__`

### PR DESCRIPTION
**Pull request by NicholasTanz**
**Description of the changes being introduced by the pull request**:

adding support for ecdsa-sha2-nistp521 in SSlibKey.verify_signature. 

Fixes #764

### CODE REVIEW

**Comment by NicholasTanz** [comment]
Hey , when adding tests in `test_signer.py` for these changes, do you know what `default_keyid` value I should use for `ecdsa-sha2-nistp521`

**Comment by lukpueh** [comment]
You can do pretty much the same as what I did in 7bf9706ad2ec619802b215cc301b4975edcd0644 for nistp384. The commit message shows how to use `openssl` to create the key pair. You just have to change the curve parameter.

To get the default keyid you could load the public key file as SSlibKey and inspect its `keyid` field:

https://github.com/secure-systems-lab/securesystemslib/blob/7bf9706ad2ec619802b215cc301b4975edcd0644/tests/test_signer.py#L332-L333

**Comment by lukpueh** [comment]
I think this looks good. Why did you convert it back to draft?

**Comment by NicholasTanz** [comment]
> I think this looks good. Why did you convert it back to draft?

I wasn't sure if I needed to add the test data for `ecdsa-sha2-nistp521` anywhere else in `test_signer.py`.

**Comment by lukpueh** [comment]
> Oh, I was checking to see if I needed to add the test data for `ecdsa-sha2-nistp521` anywhere else in `test_signer.py`.

Ah, great thinking! You should definitely add a test to `test_key_verify_signature` to see if the key actually works for our purposes. And you could also add one to  `test_verify_invalid_keytype_scheme`.

**Comment by NicholasTanz** [comment]
Hey @lukpueh, thanks for taking a look at this PR - when you get a chance, could you take another look at it

**Review by lukpueh — APPROVED** [review]
Impeccable work! Thanks, Nicholas.

**Pull request merged**
