### PR TITLE
Fix ed25519 upstream check

### PR DESCRIPTION
**Pull request by jku**
Fixes: #651 

Upgrading to github-script v5 broke this (should have read the changelog more carefully...) but the fix seems to be easy

### CODE REVIEW

**Comment by lukpueh** [comment]
Sorry, I missed this PR. @jku, do you mind fixing the conflicts? Then I'll review right away.

**Comment by jku** [comment]
I removed the improvements to uses lines, should be a clean merge now

**Review by lukpueh — APPROVED** [review]
Cross-checked with [Changelog](https://github.com/actions/github-script#v5). Should be fine.

**Comment by jku** [comment]
this does seem fixed but the workflow still fails with 'Resource not accessible by integration' when it tries to create an issue... I wonder if some setting was changed meanwhile?

**Comment by jku** [comment]
oh it was already broken since commit d082614d4d: permssions were set to none, which prevents filing an issue when needed

**Pull request merged**
