### PR TITLE
Removes unused and TUF-specific content from securesystemslib

### PR DESCRIPTION
**Pull request by awwad**
This PR carves out lots of unnecessary content in securesystemslib.  It:
- removes schemas that were unused across securesystemslib, TUF, and in-toto
- removes some functions that were unused across ssl/tuf/in-toto
- removes schemas that are specific to TUF (requires changes in TUF that will already be made in [TUF PR 846](https://github.com/theupdateframework/tuf/pull/846)) 
- marks for future removal a function that is specific to TUF (`get_targets_hash`)
- marks for future removal two compression-related functions and a compression-related exception that are currently unused across ssl/tuf/in-toto
- removes some exceptions unused across ssl/tuf/in-toto
- removes many exceptions that were TUF-specific (requires changes in TUF, already made in [TUF PR 855](https://github.com/theupdateframework/tuf/pull/855))
- removes `RELPATH_SCHEMA` and `RELPATHS_SCHEMA`, which were unnecessary/misleading and are replaced by the existing `PATH_SCHEMA` and `PATHS_SCHEMA`  (appears not to require changes in in-toto; requires changes in TUF that will already be made in [TUF PR 846](https://github.com/theupdateframework/tuf/pull/846))

It also removes or corrects relevant tests.

This largely resolves Issue #161, especially given the prior merge of PR #162.

### CODE REVIEW

**Comment by awwad** [comment]
@lukpueh
I believe this is ready for review now.  Should be very basic.  Aside from whatever you spot, I'm curious to know if it affects in-toto.  Also LMK if any of the 3 remaining, TODO-marked, functions in util.py are of use to you.

**Comment by lukpueh** [comment]
Also closes #75

**Comment by lukpueh** [comment]
@awwad, I reviewed your code and made a couple of minor additions (see https://github.com/secure-systems-lab/securesystemslib/pull/165#pullrequestreview-275003699).  
Do you think you have a minute to review my commits on top of yours?

**Comment by lukpueh** [comment]
Thanks for the review, @adityasaky. `SIGNATURES_SCHEMA` is currently still used in TUF (`@develop`) . Maybe it's being removed in one of the pending TUF PRs (haven't checked in that detail). For the time being, I doesn't hurt to keep it in securesystemslib.

**Comment by adityasaky** [comment]
Yep, I saw that! I was just wondering because it was removed then added back in. Definitely doesn't hurt to keep it around. :)

**Pull request merged**
